name: Build base template

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['13.10.0']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: link and build
        run: |
          npm install -g lerna
          lerna exec npm install
          npm run bootstrap
          npm link imba

          echo "Clone base template"
          git clone https://github.com/imba/imba-base-template ./imba-base-template
          npm install --prefix ./imba-base-template
          npm run build --prefix ./imba-base-template
